# Generated by Django 5.2.10 on 2026-02-23 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='registered_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist',
            field=models.ManyToManyField(blank=True, related_name='waitlisted_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
